// ─────────────────────────────────────────────────────────────────────────────
// mockData.ts
// UI data layer for Crypto Edge AI Camp BETA.
//
// Previously: hand-written mock array.
// Now: data is generated by the UI Data Adapter from a persistable scanner
//      fixture (fixtures/persistableScannerSample.ts).
//
// The exported types and shapes (MockCandidate, MOCK_CANDIDATES, MOCK_SUMMARY)
// are preserved so all existing components continue to work without changes.
//
// Next step: replace PERSISTABLE_SCANNER_SAMPLE with a fetch() of
//   full_output.json or a real API response to get live data.
// ─────────────────────────────────────────────────────────────────────────────

import { mapPersistableScannerOutputToUiCandidates } from "./adapters/scannerOutputAdapter";
import { PERSISTABLE_SCANNER_SAMPLE } from "./fixtures/persistableScannerSample";
import type { UiTokenCandidate } from "./types/scannerTypes";

// ── Re-export types used by components ───────────────────────────────────────

export type FinalLabel = UiTokenCandidate["finalLabel"];
export type SecurityLabel = UiTokenCandidate["securityLabel"];
export type BasicFilterStatus = UiTokenCandidate["basicFilterStatus"];

/** Shape consumed by all UI components.
 *  Maps 1:1 from UiTokenCandidate but uses snake_case field names to preserve
 *  backward compatibility with existing component code. */
export interface MockCandidate {
  id: string;
  symbol: string;
  name: string;
  chain: string;
  dex: string;
  contract_address: string;
  pair_address: string;
  source_url: string;
  price_usd: number | null;
  market_cap_usd: number;
  fdv_usd: number | null;
  liquidity_usd: number;
  volume_24h_usd: number;
  volume_market_cap_ratio: number;
  pair_age_days: number;
  basic_filter_status: BasicFilterStatus;
  security_label: SecurityLabel;
  final_label: FinalLabel;
  final_reasons: string[];
  security: {
    honeypot_status: "passed" | "failed" | "unknown";
    buy_tax: number | null;
    sell_tax: number | null;
    contract_verified: boolean | null;
    ownership_status: "renounced" | "active" | "unknown";
    liquidity_locked: boolean | null;
    liquidity_lock_days: number | null;
    mint_risk: boolean | null;
    blacklist_risk: boolean | null;
    sell_restriction_risk: boolean | null;
    top_wallet_pct: number | null;
    top_10_wallets_pct: number | null;
    risk_flags: string[];
    missing_data: string[];
  } | null;
  last_checked: string;
}

// ── Adapter: UiTokenCandidate → MockCandidate ────────────────────────────────

function toMockCandidate(u: UiTokenCandidate): MockCandidate {
  return {
    id:                      u.id,
    symbol:                  u.symbol,
    name:                    u.name,
    chain:                   u.chain,
    dex:                     u.dex,
    contract_address:        u.contractAddress,
    pair_address:            u.pairAddress,
    source_url:              u.sourceUrl,
    price_usd:               null, // price_usd not in UiTokenCandidate (not needed by UI)
    market_cap_usd:          u.marketCap,
    fdv_usd:                 null, // fdv not in UiTokenCandidate (not needed by UI)
    liquidity_usd:           u.liquidity,
    volume_24h_usd:          u.volume24h,
    volume_market_cap_ratio: u.volumeMarketCapRatio,
    pair_age_days:           u.pairAgeDays,
    basic_filter_status:     u.basicFilterStatus,
    security_label:          u.securityLabel,
    final_label:             u.finalLabel,
    final_reasons:           [
      u.mainReason,
      ...u.filterReasons,
      ...u.criticalReasons,
      ...u.warningReasons,
    ].filter((r, i, arr) => r.length > 0 && arr.indexOf(r) === i), // deduplicate
    security: u.security
      ? {
          honeypot_status:       u.security.honeypotStatus,
          buy_tax:               u.security.buyTax,
          sell_tax:              u.security.sellTax,
          contract_verified:     u.security.contractVerified,
          ownership_status:      u.security.ownershipStatus,
          liquidity_locked:      u.security.liquidityLocked,
          liquidity_lock_days:   u.security.liquidityLockDays,
          mint_risk:             u.security.mintRisk,
          blacklist_risk:        u.security.blacklistRisk,
          sell_restriction_risk: u.security.sellRestrictionRisk,
          top_wallet_pct:        u.security.topWalletPct,
          top_10_wallets_pct:    u.security.top10WalletsPct,
          risk_flags:            u.riskFlags,
          missing_data:          u.missingData,
        }
      : null,
    last_checked: u.lastCheckedAt,
  };
}

// ── Generate data from adapter ────────────────────────────────────────────────

const UI_CANDIDATES: UiTokenCandidate[] =
  mapPersistableScannerOutputToUiCandidates(PERSISTABLE_SCANNER_SAMPLE);

/** All candidates — used by ScannerRadar, WatchlistTab, RiskAlerts. */
export const MOCK_CANDIDATES: MockCandidate[] = UI_CANDIDATES.map(toMockCandidate);

/** Summary counts — used by StatCards. */
export const MOCK_SUMMARY = {
  total_candidates:          MOCK_CANDIDATES.length,
  watchlist:                 MOCK_CANDIDATES.filter((c) => c.final_label === "WATCHLIST").length,
  critical_risk:             MOCK_CANDIDATES.filter((c) => c.final_label === "CRITICAL_RISK").length,
  needs_manual_verification: MOCK_CANDIDATES.filter((c) => c.final_label === "NEEDS_MANUAL_VERIFICATION").length,
  rejected:                  MOCK_CANDIDATES.filter((c) => c.final_label === "REJECT").length,
};

/** Scan run metadata — available for future header/status bar use. */
export const MOCK_SCAN_RUN = PERSISTABLE_SCANNER_SAMPLE.scan_run;
